CUDA_VISIBLE_DEVICES=0,1,2,3 PYTHONPATH='.' python run_pretraining.py \
--train_file "pretrain_samples/training.txt" \
--data_dir "./dataset" \
--do_train true \
--do_selfsupervised \
--do_supervised \
--max_seq_length 1024 \
--image_size 224 \
--max_seq_length_decoder 512 \
--max_steps 100 \
--model_name_or_path "t5-large" \
--tokenizer_name "t5-large" \
--model_type "UdopDual" \
--output_dir "./test" \
--mae_version "mae_vit_large_patch16" \
--mae_checkpoint "mae_models/mae_pretrain_vit_large_full.pth" \
--ocr_dir "pretrain_data" \
--img_dir "pretrain_data" \
--gradient_accumulation_steps 8 \
--dataloader_num_workers 1 \
--overwrite_output_dir true \
--per_device_train_batch_size 1 \
--save_steps 50000 \
--learning_rate 5e-5 \
--warmup_ratio 0.001 \
--weight_decay 0.001 \
--whole_word_masking false